[build]

packages = ["build-essential", "libcairo2", "libcairo2-dev", "libpango1.0-0", "libpango1.0-dev", "libgdk-pixbuf2.0-0", "libgdk-pixbuf2.0-dev", "libffi-dev", "shared-mime-info", "libgobject-2.0-0"]